image: node:lts

pages:
  script:
  - yarn global add parcel-bundler
  - yarn
  - yarn build
  - mv dist public
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
  only:
  - master

